### ISSUE TITLE
Add notebook Weed Crop Detection using YOLO

### ISSUE THREAD

**Issue by ananyag309** [manikumarreddyu/AgroTech-AI#174]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

Identifying weeds and distinguish them from crops is very essential in Farming. The project aims to differentiate and identify crops from weeds. For this detection, I'm employing a few State of the Art (SOTA) architectures based on the "You only look once" (YOLO) approach. 

The dataset used here is provided at https://www.kaggle.com/datasets/vinayakshanawad/weedcrop-image-dataset/data.

### Use Case

Identifying weeds and distinguish them from crops is very essential in Farming

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by manikumarreddyu** [comment]
hi @ananyag309 if you can create frontend and api.. i will put labels here..because without froontend there is no use of it..and causing problems in cloning for others..please let me know if you can create frontend part...as of now you are simply getting projects from somewhere in other repos and pasting them here...im sorry for removing labels..if you do fronend and api part i can relabel them ..i think you understand my point...simply having notebook files does nothing..until now..which are in notebooks..all of them have frontend and api..
thank you @ananyag309
