### ISSUE TITLE
[Feature Request]: add model notebook Plant Pathogen Detection using DL

### ISSUE THREAD

**Issue by ananyag309** [manikumarreddyu/AgroTech-AI#217]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

The objective of this project is to classify images of Plants into 5 categories: Healthy, Virus, Bacteria, Fungi and Pests.

Dataset
The dataset consists of 5 subdirectories dealing with Healthy, Virus, Bacteria, Fungi and Pests: each carrying approximately 8000 images totalling to approximately 40000 images.
We downsampled to approximately 1000 images per class totalling to 5000 images.

### Use Case

The objective of this project is to classify images of Plants into 5 categories: Healthy, Virus, Bacteria, Fungi and Pests.

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by manikumarreddyu** [comment]
hi @ananyag309  no need of this...if you can create along with frontend and api ..you can go ahead..other wise please leave it

**Comment by manikumarreddyu** [comment]
hi @ananyag309 if you can create frontend and api.. i will put labels here..because without froontend there is no use of it..and causing problems in cloning for others..please let me know if you can create frontend part...as of now you are simply getting projects from somewhere in other repos and pasting them here...im sorry for removing labels..if you do fronend and api part i can relabel them ..i think you understand my point...simply having notebook files does nothing..until now..which are in notebooks..all of them have frontend and api..
thank you @ananyag309

**Comment by manikumarreddyu** [comment]
if you have any queries connect me here: https://www.linkedin.com/in/manikumarreddyu

**Comment by ananyag309** [comment]
yes i will add fronted

**Comment by manikumarreddyu** [comment]
what about api ?
