### ISSUE TITLE
Correct alignment of header

### ISSUE THREAD

**Issue by khwa04** [manikumarreddyu/AgroTech-AI#297]
![Screenshot 2024-10-11 223543](https://github.com/user-attachments/assets/36620e05-7de6-4cc3-90c4-f7d9d7f07bd6)
I want to correct the alignment of  "Company" (it's little off-center)
Please assign me this issue under GSSoC extnd. and Hacktoberfest.

**Comment by manikumarreddyu** [comment]
i am closing this issue..beacuse many deployments are wasting because of this..
we have limited deployments... i am ver sorry for that ..
hey @khwa04 dont raise any PRs.. please..it s my kind request to you..please leave this issue check for other issues..

https://www.linkedin.com/in/manikumarreddyu/

connect me here if you want clasrifcation
