### ISSUE TITLE
[Bug]: Forecast Option not working

### ISSUE THREAD

**Issue by RiteshS1** [manikumarreddyu/AgroTech-AI#53]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

After entering the city name on the Forcast Page Search-bar; nothing gets updated on the page!

### Expected behavior

The current weather of the city entered must be displayed on the page; Or atleast some response must be provided to the user.

### Add ScreenShots

![Screenshot 2024-10-02 052731](https://github.com/user-attachments/assets/52a96241-6456-42f9-b4cf-bd6cd180061b)

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by manikumarreddyu** [comment]
hey @RiteshS1 thank you so much for showing interest in this project....you explored very well . we just disabled api key that it
<img width="599" alt="image" src="https://github.com/user-attachments/assets/36015a47-cd16-46b3-b384-0a29ae2eda23">

it is not a problem...you can do onething...enable api key in your local and make the forecast responsive for all devices..as of now it is not responsive...make sure to use tailwind css for styling...

please let me know if any information is needed

**Comment by RiteshS1** [comment]
Thank you @manikumarreddyu  for assigning me this issue. 
I'll start working on it right-away!

**Comment by manikumarreddyu** [comment]
hey @RiteshS1 he propese another type of api but after many attempts we are getting erros .so we kept existing api.

so..do one thing..as of now the api calls are limited to 500 per month..so you creaate two apis with your gmail accounts and place in the code with commented lines..so in future ..we can replace the api keys..so that the forecast works well...
i think you go my point..

and if you have any ideas which need to be implemented in forecast..feel free to share here...

**Comment by RiteshS1** [comment]
Done
In StateContextProvider.jsx ; I have added the backupapi keys comment along with the api 
I checked ; everything is working fine + its responsive!

![Screenshot 2024-10-03 011625](https://github.com/user-attachments/assets/27df310f-8896-427b-80a8-ac9a78a4a23c)
